name = bubble_columns
title = Bubble Columns
description = Place soul sand under water to make a rising column of bubbles that carries you to the surface, or magma to make a whirlpool that drags you down.
depends = mcl_core, mcl_nether, playerphysics
optional_depends = mcl_player
author = nando
min_minetest_version = 5.10
